-- Otto no longer requires auth-backed database tables.
-- The current product stores onboarding/profile defaults locally in the browser
-- and uses Supabase only as an edge-function host for Gemini, Firecrawl, and ElevenLabs.
